/* eslint-env node */

import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { skillSources } from '../src/data/skills.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const generatedSkillsFilePath = path.resolve(__dirname, '../src/data/skills.generated.js')
const repoOwner = 'alanjgo'
const repoName = 'product-skills'
const repoBranch = process.env.SKILLS_REPO_BRANCH ?? 'main'
const rawBaseUrl =
  process.env.SKILLS_RAW_BASE_URL ??
  `https://raw.githubusercontent.com/${repoOwner}/${repoName}/${repoBranch}`
const requestTimeoutMs = 10000

function getInstallCommand(slug) {
  return `npx skills add ${repoOwner}/${repoName} --skill ${slug}`
}

function getSkillUrl(source) {
  return source.url ?? `${rawBaseUrl}/${source.slug}/SKILL.md`
}

async function fetchSkillMarkdown(source) {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), requestTimeoutMs)
  const url = getSkillUrl(source)

  try {
    const response = await fetch(url, {
      signal: controller.signal,
    })

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`)
    }

    return {
      markdown: await response.text(),
      sourceUrl: url,
    }
  } finally {
    clearTimeout(timeout)
  }
}

async function loadCachedSkills() {
  if (!existsSync(generatedSkillsFilePath)) {
    return new Map()
  }

  try {
    const moduleUrl = `${pathToFileURL(generatedSkillsFilePath).href}?t=${Date.now()}`
    const module = await import(moduleUrl)
    return new Map(module.skills.map((skill) => [skill.slug ?? skill.name, skill]))
  } catch (error) {
    console.warn(
      `Could not read existing generated skills cache: ${
        error instanceof Error ? error.message : 'Unknown error'
      }`
    )
    return new Map()
  }
}

function createSkillFromMarkdown(source, markdown, sourceUrl) {
  return {
    slug: source.slug,
    name: source.name ?? source.slug,
    description: source.description,
    installCommand: source.installCommand ?? getInstallCommand(source.slug),
    sourceUrl,
    content: markdown.trimEnd(),
  }
}

function createSkillFromCache(source, cachedSkill) {
  return {
    ...cachedSkill,
    slug: source.slug,
    description: '',
    installCommand: source.installCommand ?? getInstallCommand(source.slug),
    sourceUrl: cachedSkill.sourceUrl ?? getSkillUrl(source),
  }
}

function formatGeneratedSkillsFile(skills) {
  return `// This file is generated by scripts/generate-skills.js.
// GitHub SKILL.md files are the source of truth.

export const skills = ${JSON.stringify(skills, null, 2)}
`
}

async function generateSkills() {
  const cachedSkills = await loadCachedSkills()
  const skills = []
  const failures = []

  for (const source of skillSources) {
    try {
      const { markdown, sourceUrl } = await fetchSkillMarkdown(source)
      const skill = createSkillFromMarkdown(source, markdown, sourceUrl)

      skills.push(skill)
      console.log(`Updated ${skill.name} from GitHub`)
    } catch (error) {
      const cachedSkill = cachedSkills.get(source.slug)

      if (cachedSkill) {
        skills.push(createSkillFromCache(source, cachedSkill))
        console.warn(
          `Using cached ${source.slug}: ${
            error instanceof Error ? error.message : 'Unknown error'
          }`
        )
        continue
      }

      failures.push(
        `${source.slug}: ${error instanceof Error ? error.message : 'Unknown error'}`
      )
    }
  }

  if (failures.length > 0) {
    throw new Error(`Could not generate skills and no cache was available:\n${failures.join('\n')}`)
  }

  await mkdir(path.dirname(generatedSkillsFilePath), {
    recursive: true,
  })
  await writeFile(generatedSkillsFilePath, formatGeneratedSkillsFile(skills), 'utf8')
}

generateSkills().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
